sudo: required

language: python
python:
  - 3.6

services:
  - docker

before_install:
  - docker build -t arl_img:latest --build-arg PYTHON=python3.6 .

script:
  - docker run --rm -ti arl_img:latest /bin/sh -c "cd /arl && make code-analysis"
